default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: partner-metrics-dev

test:
  <<: *default
  database: partner-metrics-test
