name: Reviewdog

on: [pull_request]

env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  standard:
    uses: forsbergplustwo/github-actions/.github/workflows/standard.yml@main
    secrets:
      bundle_token: ${{ secrets.BUNDLE_TOKEN }}
